import { User, Admin, Physiotherapist, Patient, Case } from '@/app/types';

// Mock Users
export const mockAdmins: Admin[] = [
  {
    id: 'admin-1',
    name: 'Admin User',
    email: 'admin@physio.com',
    password: 'admin123', // In production, this would be hashed
    role: 'admin',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
];

export const mockPhysiotherapists: Physiotherapist[] = [
  {
    id: 'physio-1',
    name: 'Dr. John Doe',
    email: 'john.doe@physio.com',
    password: 'physio123',
    role: 'physiotherapist',
    dob: '1985-05-15',
    practicingSince: '2010-06-01',
    degrees: ['BPT', 'MPT in Orthopedics'],
    specialities: ['Sports Injury', 'Orthopedic Rehabilitation', 'Manual Therapy'],
    citiesAvailable: ['Mumbai', 'Navi Mumbai', 'Thane'],
    clinicAddresses: ['123 Marine Drive, Mumbai, Maharashtra 400001', '456 Vashi Plaza, Navi Mumbai 400703'],
    mobileNumber: '+91-9876543210',
    gender: 'male',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'physio-2',
    name: 'Dr. Sarah Smith',
    email: 'sarah.smith@physio.com',
    password: 'physio123',
    role: 'physiotherapist',
    dob: '1990-08-22',
    practicingSince: '2015-07-01',
    degrees: ['BPT', 'MPT in Neurology'],
    specialities: ['Neurological Rehabilitation', 'Stroke Recovery', 'Balance Training'],
    citiesAvailable: ['Pune', 'Mumbai'],
    clinicAddresses: ['456 FC Road, Pune, Maharashtra 411004'],
    mobileNumber: '+91-9876543211',
    gender: 'female',
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    id: 'physio-3',
    name: 'Dr. Raj Kumar',
    email: 'raj.kumar@physio.com',
    password: 'physio123',
    role: 'physiotherapist',
    dob: '1988-03-10',
    practicingSince: '2012-08-01',
    degrees: ['BPT', 'MPT in Cardiopulmonary'],
    specialities: ['Cardiopulmonary Rehabilitation', 'Post-Surgery Recovery'],
    citiesAvailable: ['Bangalore', 'Mysore'],
    clinicAddresses: ['789 MG Road, Bangalore, Karnataka 560001'],
    mobileNumber: '+91-9876543212',
    gender: 'male',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: 'physio-4',
    name: 'Dr. Priya Sharma',
    email: 'priya.sharma@physio.com',
    password: 'physio123',
    role: 'physiotherapist',
    dob: '1992-03-18',
    practicingSince: '2016-09-01',
    degrees: ['BPT', 'MPT in Sports Medicine'],
    specialities: ['Sports Rehabilitation', 'Athletic Performance', 'Injury Prevention'],
    citiesAvailable: ['Mumbai', 'Pune'],
    clinicAddresses: ['321 Andheri West, Mumbai 400053', '88 Koregaon Park, Pune 411001'],
    mobileNumber: '+91-9876543213',
    gender: 'female',
    createdAt: new Date('2024-02-05'),
    updatedAt: new Date('2024-02-05'),
  },
  {
    id: 'physio-5',
    name: 'Dr. Amit Patel',
    email: 'amit.patel@physio.com',
    password: 'physio123',
    role: 'physiotherapist',
    dob: '1987-11-25',
    practicingSince: '2011-05-15',
    degrees: ['BPT', 'MPT in Musculoskeletal'],
    specialities: ['Back Pain Management', 'Posture Correction', 'Ergonomics'],
    citiesAvailable: ['Delhi', 'Gurgaon', 'Noida'],
    clinicAddresses: ['15 Connaught Place, Delhi 110001', '42 Cyber City, Gurgaon 122002'],
    mobileNumber: '+91-9876543214',
    gender: 'male',
    createdAt: new Date('2024-02-08'),
    updatedAt: new Date('2024-02-08'),
  },
  {
    id: 'physio-6',
    name: 'Dr. Meera Reddy',
    email: 'meera.reddy@physio.com',
    password: 'physio123',
    role: 'physiotherapist',
    dob: '1991-07-14',
    practicingSince: '2014-03-01',
    degrees: ['BPT', 'MPT in Pediatrics'],
    specialities: ['Pediatric Physiotherapy', 'Developmental Delays', 'Cerebral Palsy'],
    citiesAvailable: ['Hyderabad', 'Bangalore'],
    clinicAddresses: ['67 Banjara Hills, Hyderabad 500034'],
    mobileNumber: '+91-9876543215',
    gender: 'female',
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-02-10'),
  },
  {
    id: 'physio-7',
    name: 'Dr. Vikram Singh',
    email: 'vikram.singh@physio.com',
    password: 'physio123',
    role: 'physiotherapist',
    dob: '1984-09-30',
    practicingSince: '2009-07-20',
    degrees: ['BPT', 'MPT in Geriatrics'],
    specialities: ['Geriatric Care', 'Fall Prevention', 'Arthritis Management'],
    citiesAvailable: ['Jaipur', 'Udaipur'],
    clinicAddresses: ['234 MI Road, Jaipur 302001'],
    mobileNumber: '+91-9876543216',
    gender: 'male',
    createdAt: new Date('2024-02-12'),
    updatedAt: new Date('2024-02-12'),
  },
  {
    id: 'physio-8',
    name: 'Dr. Anjali Desai',
    email: 'anjali.desai@physio.com',
    password: 'physio123',
    role: 'physiotherapist',
    dob: '1993-05-08',
    practicingSince: '2017-08-10',
    degrees: ['BPT', 'MPT in Women\'s Health'],
    specialities: ['Prenatal Care', 'Postnatal Rehabilitation', 'Pelvic Floor Therapy'],
    citiesAvailable: ['Ahmedabad', 'Surat'],
    clinicAddresses: ['56 SG Highway, Ahmedabad 380015'],
    mobileNumber: '+91-9876543217',
    gender: 'female',
    createdAt: new Date('2024-02-14'),
    updatedAt: new Date('2024-02-14'),
  },
];

export const mockPatients: Patient[] = [
  {
    id: 'patient-1',
    name: 'Alice Johnson',
    email: 'alice@example.com',
    password: 'patient123',
    role: 'patient',
    age: 37,
    city: 'Mumbai',
    mobileNumber: '+91-9123456780',
    gender: 'female',
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-02-10'),
  },
  {
    id: 'patient-2',
    name: 'Bob Williams',
    email: 'bob@example.com',
    password: 'patient123',
    role: 'patient',
    age: 44,
    city: 'Pune',
    mobileNumber: '+91-9123456781',
    gender: 'male',
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-02-15'),
  },
  {
    id: 'patient-3',
    name: 'Charlie Brown',
    email: 'charlie@example.com',
    password: 'patient123',
    role: 'patient',
    age: 30,
    city: 'Bangalore',
    mobileNumber: '+91-9123456782',
    gender: 'male',
    createdAt: new Date('2024-02-20'),
    updatedAt: new Date('2024-02-20'),
  },
  {
    id: 'patient-4',
    name: 'Diana Martinez',
    email: 'diana@example.com',
    password: 'patient123',
    role: 'patient',
    age: 57,
    city: 'Mumbai',
    mobileNumber: '+91-9123456783',
    gender: 'female',
    createdAt: new Date('2024-02-25'),
    updatedAt: new Date('2024-02-25'),
  },
  {
    id: 'patient-5',
    name: 'Ethan Hunt',
    email: 'ethan@example.com',
    password: 'patient123',
    role: 'patient',
    age: 36,
    city: 'Delhi',
    mobileNumber: '+91-9123456784',
    gender: 'male',
    createdAt: new Date('2024-02-26'),
    updatedAt: new Date('2024-02-26'),
  },
  {
    id: 'patient-6',
    name: 'Fiona Gallagher',
    email: 'fiona@example.com',
    password: 'patient123',
    role: 'patient',
    age: 32,
    city: 'Hyderabad',
    mobileNumber: '+91-9123456785',
    gender: 'female',
    createdAt: new Date('2024-02-27'),
    updatedAt: new Date('2024-02-27'),
  },
  {
    id: 'patient-7',
    name: 'George Martin',
    email: 'george@example.com',
    password: 'patient123',
    role: 'patient',
    age: 41,
    city: 'Pune',
    mobileNumber: '+91-9123456786',
    gender: 'male',
    createdAt: new Date('2024-02-28'),
    updatedAt: new Date('2024-02-28'),
  },
  {
    id: 'patient-8',
    name: 'Hannah Baker',
    email: 'hannah@example.com',
    password: 'patient123',
    role: 'patient',
    age: 28,
    city: 'Mumbai',
    mobileNumber: '+91-9123456787',
    gender: 'female',
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-03-01'),
  },
  {
    id: 'patient-9',
    name: 'Ian Malcolm',
    email: 'ian@example.com',
    password: 'patient123',
    role: 'patient',
    age: 39,
    city: 'Bangalore',
    mobileNumber: '+91-9123456788',
    gender: 'male',
    createdAt: new Date('2024-03-02'),
    updatedAt: new Date('2024-03-02'),
  },
  {
    id: 'patient-10',
    name: 'Julia Roberts',
    email: 'julia@example.com',
    password: 'patient123',
    role: 'patient',
    age: 30,
    city: 'Ahmedabad',
    mobileNumber: '+91-9123456789',
    gender: 'female',
    createdAt: new Date('2024-03-03'),
    updatedAt: new Date('2024-03-03'),
  },
  {
    id: 'patient-11',
    name: 'Kevin Hart',
    email: 'kevin@example.com',
    password: 'patient123',
    role: 'patient',
    age: 35,
    city: 'Jaipur',
    mobileNumber: '+91-9123456790',
    gender: 'male',
    createdAt: new Date('2024-03-04'),
    updatedAt: new Date('2024-03-04'),
  },
  {
    id: 'patient-12',
    name: 'Laura Croft',
    email: 'laura@example.com',
    password: 'patient123',
    role: 'patient',
    age: 33,
    city: 'Thane',
    mobileNumber: '+91-9123456791',
    gender: 'female',
    createdAt: new Date('2024-03-05'),
    updatedAt: new Date('2024-03-05'),
  },
];

export const mockCases: Case[] = [
  {
    id: 'case-1',
    patientId: 'patient-1',
    physiotherapistId: 'physio-1',
    issueDetails: 'Lower back pain after sports injury. Pain increases during bending and lifting.',
    city: 'Mumbai',
    canTravel: true,
    status: 'open',
    comments: [
      {
        id: 'comment-1',
        userId: 'physio-1',
        userName: 'Dr. John Doe',
        userRole: 'physiotherapist',
        message: 'Initial assessment completed. Starting with heat therapy and stretching exercises.',
        timestamp: new Date('2024-02-12T10:00:00'),
      },
      {
        id: 'comment-2',
        userId: 'patient-1',
        userName: 'Alice Johnson',
        userRole: 'patient',
        message: 'Feeling better after the first session. Pain has reduced slightly.',
        timestamp: new Date('2024-02-13T14:30:00'),
      },
      {
        id: 'comment-3',
        userId: 'physio-1',
        userName: 'Dr. John Doe',
        userRole: 'physiotherapist',
        message: 'Good progress. Continue with home exercises. Next session in 2 days.',
        timestamp: new Date('2024-02-14T11:00:00'),
      },
    ],
    createdAt: new Date('2024-02-11'),
    updatedAt: new Date('2024-02-14'),
  },
  {
    id: 'case-2',
    patientId: 'patient-2',
    physiotherapistId: 'physio-2',
    issueDetails: 'Post-stroke rehabilitation needed. Limited mobility in right arm and leg.',
    city: 'Pune',
    canTravel: false,
    status: 'open',
    comments: [
      {
        id: 'comment-4',
        userId: 'physio-2',
        userName: 'Dr. Sarah Smith',
        userRole: 'physiotherapist',
        message: 'Starting with range of motion exercises and electrical stimulation therapy.',
        timestamp: new Date('2024-02-16T09:00:00'),
      },
      {
        id: 'comment-5',
        userId: 'patient-2',
        userName: 'Bob Williams',
        userRole: 'patient',
        message: 'Sessions are helpful. I can move my fingers a bit more now.',
        timestamp: new Date('2024-02-18T16:00:00'),
      },
    ],
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-02-18'),
  },
  {
    id: 'case-3',
    patientId: 'patient-3',
    issueDetails: 'Knee pain after running. Swelling and difficulty in walking.',
    city: 'Bangalore',
    canTravel: true,
    preferredGender: 'male',
    status: 'open',
    comments: [],
    createdAt: new Date('2024-02-20'),
    updatedAt: new Date('2024-02-20'),
  },
  {
    id: 'case-4',
    patientId: 'patient-4',
    physiotherapistId: 'physio-1',
    issueDetails: 'Shoulder pain and stiffness. Difficulty in raising arm above head.',
    city: 'Mumbai',
    canTravel: true,
    status: 'pending_closure',
    closureRequestedBy: 'physio-1',
    closureRequestTimestamp: new Date('2024-01-30'),
    comments: [
      {
        id: 'comment-6',
        userId: 'physio-1',
        userName: 'Dr. John Doe',
        userRole: 'physiotherapist',
        message: 'Treatment has been successful. Patient has regained full range of motion. Recommending case closure.',
        timestamp: new Date('2024-01-30T10:00:00'),
      },
    ],
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-30'),
  },
];

export const mockUsers: User[] = [
  ...mockAdmins,
  ...mockPhysiotherapists,
  ...mockPatients,
];

// Helper functions
export const findUserByEmail = (email: string): User | undefined => {
  return mockUsers.find((user) => user.email === email);
};

export const findUserById = (id: string): User | undefined => {
  return mockUsers.find((user) => user.id === id);
};

export const findCasesByPatientId = (patientId: string): Case[] => {
  return mockCases.filter((c) => c.patientId === patientId);
};

export const findCasesByPhysiotherapistId = (physiotherapistId: string): Case[] => {
  return mockCases.filter((c) => c.physiotherapistId === physiotherapistId);
};

export const findUnmappedCasesByCity = (city: string): Case[] => {
  return mockCases.filter((c) => !c.physiotherapistId && c.city === city);
};

export const getPhysiotherapistsByCity = (city: string): Physiotherapist[] => {
  return mockPhysiotherapists.filter((p) => p.citiesAvailable.includes(city));
};
